### ISSUE TITLE
Ticket to identify the changes to the submission api that requires an update to the wrapper

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/topcoder-submission-api-wrapper#8]
- [ ] Add legacyReviewId to `review` [Reference](https://github.com/topcoder-platform/submissions-api/issues/143)

- [ ] New metadata structure for `review` [Reference](https://github.com/topcoder-platform/submissions-api/issues/137)

- [ ] New status attribute to `review` [Reference](https://github.com/topcoder-platform/submissions-api/issues/130). Note that this has a default value of `completed`

- [ ] Update artifact payload structure for submission [Reference](https://github.com/topcoder-platform/submissions-api/issues/125)

- [ ] Support sortBy query param for submission [Reference](https://github.com/topcoder-platform/submissions-api/issues/124)

**Comment by callmekatootie** [comment]
From contest https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30103143
